FROM ruby:2.4.1

# timezone
RUN cp /usr/share/zoneinfo/Asia/Tokyo /etc/localtime

EXPOSE 3000

# create user
RUN useradd port -u 3333 -d /home/port && \
    mkdir -p /home/port/app && \
    chown port.port -R /home/port
WORKDIR /home/port/app

# install dependency package
RUN apt-get update
RUN apt-get install -y apt-transport-https libssl-dev

# install nodejs
USER port
RUN curl -s -L git.io/nodebrew | perl - setup
ENV PATH /home/port/.nodebrew/current/bin:$PATH
RUN nodebrew install-binary v8.7.0
RUN nodebrew use v8.7.0
USER root

# install yarn
# https://yarnpkg.com/en/docs/install#linux-tab
RUN curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
RUN echo "deb https://dl.yarnpkg.com/debian/ stable main" | tee /etc/apt/sources.list.d/yarn.list
RUN apt-get update
RUN apt-get install -y yarn

RUN gem install bundler

COPY . /home/port/app

# bundle install
RUN bundle install --without development test --path vendor/bundle

# yarn install
RUN yarn install

# assets precompile
RUN RAILS_ENV=production bundle exec rails assets:precompile

RUN chown port.port log && \
    chown port.port -R db
USER port

CMD bundle exec puma -t 5:5 -p 3000 -e "$RAILS_ENV" -C config/puma.rb
